M48
; DRILL file {KiCad (6.0.5)} date Mon Feb 13 16:39:51 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-02-13T16:39:51+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.5)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X4.6Y-2.0
X5.1Y-4.7
X5.9Y-2.0
X6.7Y-3.4
X8.2Y-2.0
X8.2Y-4.7
T0
M30
